config/routes.rb
# Because of plugin deactivations
if Redmine::Plugin.installed?(:easy_gantt_pro)
  scope format: true, defaults: { format: 'json' }, constraints: { format: 'json' } do
    put 'easy_gantt/reschedule_project/:id', to: 'easy_gantt#reschedule_project', as: 'easy_gantt_reschedule_project'
    post 'easy_gantt/lowest_progress_tasks', to: 'easy_gantt_pro#lowest_progress_tasks', as: 'easy_gantt_lowest_progress_tasks'
  end

  scope 'easy_gantt', controller: 'easy_gantt_pro', as: 'easy_gantt' do
    scope format: true, defaults: { format: 'json' }, constraints: { format: 'json' } do
      match 'cashflow_data', via: [:get, :post]
    end

    get 'recalculate_fixed_delay'
  end
end

app/controllers/easy_gantt_pro_controller.rb
class EasyGanttProController < EasyGanttController
  accept_api_auth :lowest_progress_tasks, :cashflow_data

  before_action :require_admin, only: [:recalculate_fixed_delay]

  # TODO: Calculate progress date on DB
  def lowest_progress_tasks
    project_ids = Array(params[:project_ids])

    @data = Hash.new { |hash, key| hash[key] = { date: Date.new(9999), ids: [] } }

    issues = Issue.open.joins(:status).
                   where(project_id: project_ids).
                   where.not(start_date: nil, due_date: nil).
                   pluck(:project_id, :id, :start_date, :due_date, :done_ratio)

    issues.each do |p_id, i_id, start_date, due_date, done_ratio|
      diff = due_date - start_date
      add_days = (diff * done_ratio.to_i) / 100
      progress_date = start_date + add_days.days

      project_data = @data[p_id]
      if project_data[:date] == progress_date
        project_data[:ids] << i_id
      elsif project_data[:date] > progress_date
        project_data[:date] = progress_date
        project_data[:ids] = [i_id]
      end
    end

    ids = @data.flat_map{|_, data| data[:ids]}
    @issues = Issue.select(:project_id, :id, :subject).where(id: ids)
  end

  def cashflow_data
    unless EasyGantt.easy_money?
      return render_404
    end

    project_ids = Array(params[:project_ids])

    @data = Hash.new { |hash, key| hash[key] = { revenues: [], expenses: [] } }

    revenues = EasyMoneyExpectedRevenue.where(project_id: project_ids).pluck(:project_id, :spent_on, :price1)
    revenues.each do |project_id, spent_on, price1|
      @data[project_id][:revenues] << {spent_on: spent_on, price1: price1}
    end

    expenses = EasyMoneyExpectedExpense.where(project_id: project_ids).pluck(:project_id, :spent_on, :price1)
    expenses.each do |project_id, spent_on, price1|
      @data[project_id][:expenses] << {spent_on: spent_on, price1: price1}
    end
  end

  def recalculate_fixed_delay
    statuses = [Project::STATUS_ACTIVE]
    if EasyGantt.easy_extensions?
      statuses << Project::STATUS_PLANNED
    end

    issues = Issue.joins(:project).where(projects: { status: statuses })
    relations = IssueRelation.preload(:issue_from, :issue_to).
                              where(relation_type: IssueRelation::TYPE_PRECEDES).
                              where(issue_from_id: issues, issue_to_id: issues).
                              where.not(delay: nil)

    relations.each do |relation|
      next if relation.issue_from.nil? || relation.issue_to.nil?

      from = relation.issue_from.due_date || relation.issue_from.start_date
      to = relation.issue_to.start_date || relation.issue_to.due_date

      next if from.nil? || to.nil?

      saved_delay = relation.delay
      correct_delay = (to-from-1).to_i

      if saved_delay != correct_delay
        relation.update_column(:delay, correct_delay)
      end
    end

    flash[:notice] = l(:notice_easy_gantt_fixed_delay_recalculated)
    redirect_to :back
  end

end

app/views/easy_gantt_pro/_gantt_tools.html.erb
<% if EasyGantt.easy_extensions? %>
  <label for="select_scheme_select"><%= l(:label_easy_color_schemes) %></label>
  <select id="select_scheme_select" style="width: auto" title="<%= l('easy_gantt.scheme_by.label_color_by') %>:">
    <% if @project %>
      <option value="issue_priority"><%= l('easy_gantt.scheme_by.label_by_priority') %></option>
      <option value="issue_status"><%= l('easy_gantt.scheme_by.label_by_status') %></option>
      <option value="tracker"><%= l('easy_gantt.scheme_by.label_by_tracker') %></option>
    <% else %>
      <option value="project_priority"><%= l('easy_gantt.scheme_by.label_by_priority') %></option>
      <option value="project_status"><%= l('easy_gantt.scheme_by.label_by_status') %></option>
    <% end %>
  </select>
<% end %>

app/views/easy_gantt_pro/_includes.html.erb
<% include_calendar_headers_tags %>
<%= easy_gantt_include_css('easy_gantt_pro', media: 'all', from_plugin: 'easy_gantt_pro') %>
<% if EasyGantt.combine_by_pipeline?(params) %>
  <% if @project %>
    <%= javascript_include_tag('easy_gantt_pro/easy_gantt_pro') %>
  <% else %>
    <%= javascript_include_tag('easy_gantt_pro/easy_gantt_pro_global') %>
  <% end %>
<% else %>
  <% # DONT FORGET TO ADD FILE INTO {plugin}.js !!!!! %>
  <%= easy_gantt_include_js(
          'common', 'sorting', 'email_silencer',
          (['baseline', 'add_task'] if @project),
          ('critical'         if @project && EasySetting.value(:easy_gantt_critical_path) != 'disabled'),
          ('grid_context'     if @project && EasyGantt.easy_extensions?),
          ('project_move'     if @project.nil?),
          ('lowest_progress'  if @project.nil? && EasySetting.value(:easy_gantt_show_lowest_progress_tasks)),
          ('delayed_projects' if @project.nil? && EasySetting.value(:easy_gantt_show_project_progress)),
          ('gg_resource'      if @project.nil? && EasyGantt.easy_gantt_resources?),
          ('schemes'          if EasyGantt.easy_extensions?),
          ('cashflow'         if EasyGantt.easy_money?),
          ('fixed_delay'      if EasyGantt.load_fixed_delay?),
          ('delayed_issues'   if params[:controller] == 'easy_gantt'),
          from_plugin: 'easy_gantt_pro')
  %>
<% end %>

app/views/easy_gantt_pro/_js_prepare.html.erb
<%
  subproject_gantt_params = query.to_params.merge(key: User.current.api_key, subproject_loading: '1', opened_project_id: ':projectID', format: 'json')

  subproject_gantt_path = if @project
    issues_easy_gantt_path(@project.id, subproject_gantt_params)
  else
    projects_easy_gantt_path(subproject_gantt_params)
  end

  conditional_paths = {}

  if EasyGantt.easy_extensions?
    conditional_paths[:issueFormFields] = url_for(controller: 'easy_issues', action: 'form_fields', format: 'json', project_id: nil, id: '__issueId')
    conditional_paths[:projectFormFields] = url_for(controller: 'easy_issues', action: 'form_fields', format: 'json', project_id: '__projectId')
  end

  if @project && EasyGantt.easy_baseline?
    conditional_paths[:baselineRoot] = project_easy_baselines_path(@project, key: User.current.api_key, format: 'json')
    conditional_paths[:baselineGET] = easy_baseline_gantt_path(':baselineID', key: User.current.api_key, format: 'json')
    conditional_paths[:baselineDELETE] = project_easy_baseline_path(@project, ':baselineID', key: User.current.api_key, format: 'json')
  end

  if EasyGantt.easy_money?
    conditional_paths[:cashflow] = easy_gantt_cashflow_data_path(project_id: @project, key: User.current.api_key)
  end
%>

<script type="text/javascript">
  window.ysy = window.ysy || {};
  ysy.settings = ysy.settings || {};
  $.extend(true, ysy.settings, <%= {
      criticalType: EasySetting.value(:easy_gantt_critical_path),
      showLowestProgress: EasySetting.value(:easy_gantt_show_lowest_progress_tasks),
      showProjectProgress: EasySetting.value(:easy_gantt_show_project_progress),
      paths: {
        subprojectGantt: subproject_gantt_path.html_safe,
        newIssuePath: new_issue_path(key: User.current.api_key),
        newMilestonePath: new_project_version_path(':projectID', key: User.current.api_key),
        projectPUT: easy_gantt_reschedule_project_path(':projectID', format: 'json', key: User.current.api_key),
        lowestProgressTasks: easy_gantt_lowest_progress_tasks_path(key: User.current.api_key),
        projectOpenedIssues: project_issues_easy_gantt_path(':projectID', key: User.current.api_key)
      }.merge(conditional_paths),
      labels: {
        buttons: {
          create: l(:button_create)
        },
        critical: {
          legend: l('easy_gantt_pro.critical.legend_issues')
        },
        properties:{
          tracker: l(:field_tracker),
          status: l(:field_status),
          priority: l(:field_priority),
          assigned_to: l(:field_assigned_to),
          activity: l(:field_activity),
          category: l(:field_category),
          done_ratio: l(:field_done_ratio),
          fixed_version: l(:field_fixed_version)
        },
        baselines: {
          baseline: l('easy_gantt_pro.baselines.label_baseline'),
          startDate: l(:field_start_date),
          dueDate: l(:field_due_date),
          createButton: l(:button_create),
          deleteButton: l(:button_delete),
          confirm_delete: l('easy_gantt_pro.baselines.confirm_delete'),
          delete_failed: l('easy_gantt_pro.baselines.delete_failed'),
          error_not_saved: l('easy_gantt_pro.baselines.error_not_saved'),
          label_same: l('easy_gantt_pro.baselines.label_same')
        },
        baselineCreateModal: {
          request_failed: l('easy_gantt_pro.baselines.create_failed')
        },
        addTask: {
          error_blank: l('activerecord.errors.messages.blank')
        },
        projectMove: {
          error_opening_unsaved: l('easy_gantt_pro.project_move.error_opening_unsaved')
        },
        resources: {
          label_resources: l('easy_gantt_pro.resources.label_resources')
        },
        silencer: {
          label_disable_notifications: l(:label_disable_notifications)
        }
      },
      datepickerOptions: {
        dateFormat: 'yy-mm-dd',
        firstDay: 1,
        showOn: 'button',
        buttonImageOnly: true,
        buttonImage: "#{home_path}images/calendar.png",
        showButtonPanel: true,
        showWeek: true,
        showOtherMonths: true,
        selectOtherMonths: true,
        changeMonth: true,
        changeYear: true
      }
    }.to_json.html_safe %>);

  ysy.view = ysy.view || {};
  ysy.view.templates = ysy.view.templates || {};
  $.extend(true, ysy.view.templates, <%= {
      BaselineOption: %{
       {{#baselines}}<option id="baseline_option_{{id}}" value="{{id}}"{{selected}}>{{name}}</option>{{/baselines}}
      },
      errorExplanation: %{
        <div id="errorExplanation">
          <ul>
          {{#problems}}
          <li>{{.}}</li>
          {{/problems}}
          </ul>
        </div>
      },
      baselineCreateModal: %{
        <h3 class="title">#{l('easy_gantt.popup.baseline.heading_new_baseline')}</h3>
        <form class="tabular">
        <p>
          <label for="baseline_modal_name">#{l(:field_name)}</label>
          <input type="text" placeholder="{{generic}}" id="baseline_modal_name" size="50">
        </p>
        </form>
      },
      lowestProgressText: %{
        <div title="{{#issues}}\#{{id}} {{name}}\n{{/issues}}(#{l('easy_gantt_pro.lowest_progress.label_progress_date')}: {{progress_date}})">
          {{#issues}}
          <a href="{{url}}" target="_blank">{{name}}</a>
          {{/issues}}
          & (#{l('easy_gantt_pro.lowest_progress.label_progress_date')}: {{progress_date}})
        </div>
      },
      CashflowTooltip: %{
        <h3 class="gantt-tooltip-header">Cashflow</h3>
        {{#dates}}
        <div class="gantt-tooltip-cashflow-day{{#first}} gantt-tooltip-cashflow-day-first{{/first}}">
          <div class="gantt-tooltip-cashflow-left">{{date}}</div>
          <div class="gantt-tooltip-cashflow-right">
            {{#revenues}}
            <div>Amount: <span class="gantt-tooltip-cashflow-price">{{price1}}</span></div>
            {{/revenues}}
            {{#expenses}}
            <div>Amount: <span class="gantt-tooltip-cashflow-price negative">- {{price1}}</span></div>
            {{/expenses}}
          </div>
        </div>
        {{/dates}}
      },
      gridContext: %{
        <ul>
        {{#menu}}
          {{^hasMenu}}
          <li>
            <a class="{{icon}} {{className}}" href="{{href}}">{{name}}</a>
          {{/hasMenu}}
          {{#hasMenu}}
          <li class="folder">
            <a href="javascript:void(0)" class="submenu {{icon}}">{{name}}</a>
            <ul data-property="{{property}}">
              {{#folder}}
                <li>
                  <a class="gantt-context-leaf{{#isChecked}} icon-checked{{/isChecked}}{{#isDisabled}} disabled{{/isDisabled}}" href="javascript:void(0)" data-value="{{value}}">{{name}}</a>
                </li>
              {{/folder}}
            </ul>
          {{/hasMenu}}
          </li>
        {{/menu}}
        </ul>
      }
    }.to_json.html_safe %>)
</script>

app/views/easy_gantt_pro/_test_includes.erb
<%= easy_gantt_include_js(
        # common tests
        'jasmine/grid_context',
        from_plugin: 'easy_gantt_pro') %>

app/views/easy_page_modules/projects/_easy_global_gantt_show.html.erb
<% if easy_page_modules_data[:query].nil? %>
  <p>
    <%= l(:label_easy_page_module_settings_missing) %>
  </p>
<% else %>
  <%= render template: 'easy_gantt/index', locals: { show_query: false,
                                                     query: easy_page_modules_data[:query] } %>
<% end %>

app/views/easy_page_modules/projects/_easy_project_gantt_show.html.erb
<% if easy_page_modules_data[:query].nil? %>
  <p>
    <%= l(:label_easy_page_module_settings_missing) %>
  </p>
<% elsif easy_page_modules_data[:can_view] %>
  <%= render template: 'easy_gantt/index', locals: { show_query: false,
                                                     query: easy_page_modules_data[:query] } %>
<% else %>
  <p>
    <%= l(:error_easy_gantt_view_permission) %>
  </p>
<% end %>

app/views/easy_settings/_easy_gantt_pro.html.erb
<% # Its a hook only !!! %>

<p>
  <%= form.label :fixed_delay, l(:field_easy_gantt_fixed_delay) %>
  <%#= form.check_box :fixed_delay %>
  <!--<em class="small"><%#= l(:text_easy_gantt_fixed_delay) %></em>-->
  <!--<br>-->
  <span id="recalculate-fixed-delay" class="<%#= 'hidden' if !form.object.fixed_delay %>">
    <%= link_to l(:label_easy_gantt_recalculate_fixed_delay), easy_gantt_recalculate_fixed_delay_path, data: { confirm: l(:warning_easy_gantt_recalculate_fixed_delay) } %>
  </span>
</p>

<p>
  <%= form.label l(:label_easy_gantt_critical_path) %>

  <label class="radio block">
    <%= form.radio_button :critical_path, 'disabled' %>
    <%= l('easy_gantt.critical_path.disabled') %>
  </label>

  <label class="radio block">
    <%= form.radio_button :critical_path, 'last' %>
    <%= l('easy_gantt.critical_path.last') %>
    <em>(<%= l('easy_gantt.critical_path.last_text') %>)</em>
  </label>

  <label class="radio block">
    <%= form.radio_button :critical_path, 'longest' %>
    <%= l('easy_gantt.critical_path.longest') %>
    <em>(<%= l('easy_gantt.critical_path.longest_text') %>)</em>
  </label>
</p>

<p>
  <%= form.label l(:label_show_lowest_progress_tasks) %>
  <%= form.check_box :show_lowest_progress_tasks %>
  <br>
  <em class="small"><%= l(:text_show_lowest_progress_tasks) %></em>
</p>

<script>
  // $("#easy_setting_fixed_delay").on("change", function(){
  //   $("#recalculate-fixed-delay").css("display", (this.checked ? "inline" : "none"))
  // })
</script>

app/views/hooks/easy_gantt_pro/_view_easy_gantt_index_bottom.html.erb
<%= render 'easy_gantt_pro/test_includes' if params[:run_jasmine_tests] || params[:spec] %>

<%= content_for :header_tags do %>
  <%= render 'easy_gantt_pro/includes', project: @project, query: query %>
  <%= render 'easy_gantt_pro/js_prepare', project: @project, query: query %>
<% end %>

app/views/hooks/easy_gantt_pro/_view_easy_gantts_issues_toolbars.html.erb
<% if @project && Redmine::Plugin.installed?(:easy_baseline) && @project.module_enabled?('easy_baselines') %>
  <% baselines = Project.where(easy_baseline_for: @project) %>

  <div id="baseline_panel" class="contextual gantt-menu-sub-panel" style="display: none">
    <%= select_tag(:baseline_select, options_from_collection_for_select(baselines, :id, :name), class: 'gantt-baseline-toolbar-select') %>

    <% if User.current.allowed_to?(:edit_baselines, @project) %>
      <%= easy_gantt_js_button l(:button_delete), id: 'baseline_delete', icon: 'icon-del', data: { confirmation: l(:text_are_you_sure) } %>
      <%= easy_gantt_js_button l(:button_create), id: 'baseline_create', icon: 'icon-save' %>
    <% end %>

    <%= easy_gantt_help_button(:baseline, no_button: true) %>
  </div>
<% end %>

<div id="critical_panel" class="contextual gantt-menu-sub-panel" style="display: none">
  <span class="gantt-color-square" style="border: 1px solid rgba(200,0,255,1); background-color: rgba(200,0,255,0.1)"></span>
  <span><%= raw l('easy_gantt_pro.critical.legend_issues') %></span>
  <%= easy_gantt_js_button :show_only_critical, id: 'button_show_only_critical' %>
  <a id="critical_show" class="gantt-menu-button button button-2 icon icon-zoom-in" href="javascript:void(0)">
    <%= l('easy_gantt_pro.critical.show_button') %>
  </a>
  <%= easy_gantt_help_button(:critical, no_button: true) %>
</div>

<div id="add_task_panel" class="contextual gantt-menu-sub-panel" style="display: none">
  <% if @project && User.current.allowed_to?(:add_issues, @project) %>
    <a id="add_task_issue" class="add_task_type gantt-menu-button button button-2 primary icon icon-add" href="javascript:void(0)"><%= l(:label_issue_new) %></a>
  <% end %>

  <% if @project && User.current.allowed_to?(:manage_versions, @project) %>
    <a id="add_task_milestone" class="add_task_type gantt-menu-button button button-2 icon icon-add" href="javascript:void(0)"><%= l(:label_version_new) %></a>
  <% end %>

  <%= easy_gantt_help_button(:add_task, no_button: true) %>
  <span style="display: inline-block; width: 500px"></span>
</div>